# 左再起なし

expr ::= term expr_ ;
expr_ ::=  "+" term expr_ | "-" term expr_ | ;

term ::= num term_ ;
term_ ::= "*" num term_ | "/" num term_ | ;

num ::= "(" expr ")" | "-" pos | pos ;



# 左再起あり

expr ::= term | expr "+" term | expr "-" term ;

term ::= num | term "*" num | term "/" num ;

num ::= "(" expr ")" | "-" pos | pos ;

# numの正規表現
# "3."は許容しない "03.0"は許容
pos ::= ([0-9]+)(.[0-9]+)?

# "3." "03" "3.0" は許容しない
pos ::= (0|([1-9][0-9]*))(.[0-9]*[1-9])?